version: '3'

services:
    api_yamdb:
        build: .
        container_name: api_yamdb
        command: python api_yamdb/manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/opt/project
#            - ../tests/opt
        ports:
            - "8000:8000"
